[build]
builder = "nixpacks"

[deploy]
startCommand = "panel serve app.py --port=$PORT --allow-websocket-origin=$RAILWAY_STATIC_URL --show"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
